const fields = [
  { label: "Employee Code", value: "Employee Code" },
  { label: "First_Name", value: "First Name" },
  { label: "Middle Name", value: "Middle Name" },
  { label: "Last Name", value: "Last Name" },
  { label: "Dob", value: "Dob" },
  { label: "Gender", value: "Gender" },
  { label: "Employement Status", value: "Employement Status" },
  { label: "State", value: "State" },
  { label: "Street", value: "Street" },
  { label: "City", value: "City" },
  { label: "Landmark", value: "Landmark" },
  { label: "Postal Code", value: "Postal Code" },
  { label: "Country", value: "Country" },
  { label: "Phone Number", value: "Phone Number" },
  { label: "Other Phone Number", value: "Other Phone Number" },
  { label: "Personal Email", value: "Personal Email" },
  { label: "Office Email", value: "Office Email" },
  { label: "Level", value: "Level" },
  { label: "Designation", value: "Designation" },
  { label: "Department", value: "Department" },
  { label: "Team", value: "Team" },
  { label: "Role", value: "Role" },
  { label: "Manager Id", value: "Manager Id" },
  {
    label: "Emergency Contact First Name",
    value: "Emergency Contact First Name",
  },
  {
    label: "Emergency Contact Middle Name",
    value: "Emergency Contact Middle Name",
  },
  {
    label: "Emergency Contact Last Name",
    value: "Emergency Contact Last Name",
  },
  { label: "Emergency Contact Mobile", value: "Emergency Contact Mobile" },
  { label: "Email", value: "Email" },
  { label: "Relationship", value: "Relationship" },
  { label: "Bank Name", value: "Bank Name" },
  { label: "Ifsc Code", value: "Ifsc Code" },
  { label: "Account Number", value: "Account Number" },
  { label: "error", value: "error" },
];

// const fields = {
//   employee_code: "employee_code",
//   first_name: "first_name",
//   middle_name: "middle_name",
//   last_name: "last_name",
//   dob: "dob",
//   gender: "gender",
//   status: "status",
//   street: "street",
//   city: "city",
//   landmark: "landmark",
//   postal_code: "postal_code",
//   country: "country",
//   phone_number: "phone_number",
//   other_phone_number: "other_phone_number",
//   personal_email: "personal_email",
//   office_email: "office_email",
//   level: "level",
//   designation: "designation",
//   department: "department",
//   team: "team",
//   role: "role",
//   manager_id: "manager_id",
//   ec_first_name: "ec_first_name",
//   ec_middle_name: "ec_middle_name",
//   ec_last_name: "ec_last_name",
//   ec_mobile: "ec_mobile",
//   email: "email",
//   relationship: "relationship",
//   bank_name: "bank_name",
//   ifsc_code: "ifsc_code",
//   account_number: "account_number",
//   error: "error"
// }

export { fields };
